const STATIC_ASSETS = [
  '/',
  '/index.html',
  '/manifest.webmanifest',
  '/styles/main.css',
  '/src/app.js',
  '/src/router.js',
  '/src/state.js',
  '/src/ui/remote.js',
  '/src/ui/devices.js',
  '/src/ui/settings.js',
  '/src/ui/diagnostics.js',
  '/src/tv/TVAdapter.js',
  '/src/tv/SamsungAdapter.js',
  '/src/tv/LGAdapter.js',
  '/src/tv/AndroidTVAdapter.js',
  '/src/tv/GoogleTVAdapter.js',
  '/src/tv/GenericAdapter.js'
];
